application: json-service
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /echo.*
  script: echo.py
- url: /time
  script: time_app.py
- url: /sleep
  script: sleep_app.py
